<a href="https://colab.research.google.com/github/prakriti-khadka11/Concept-and-Technologies-of-Ai/blob/main/worksheet5_Prakriti_Khadka2431868.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

dataSet=pd.read_csv("/content/drive/MyDrive/data/student.csv")
headData=dataSet.head()
print("This is the most top data : \n" ,headData,"\n")

This is the most top data : 
    Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62 



In [12]:
tailData=dataSet.tail()
print("This is the most button data :\n" ,tailData,"\n" )


This is the most button data :
      Math  Reading  Writing
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72 



In [13]:
dataInfo=dataSet.info
print("Basic info of the given dataset:" ,dataInfo,"\n")


Basic info of the given dataset: <bound method DataFrame.info of      Math  Reading  Writing
0      48       68       63
1      62       81       72
2      79       80       78
3      76       83       79
4      59       64       62
..    ...      ...      ...
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72

[1000 rows x 3 columns]> 



In [14]:
dataDesc=dataSet.describe()
print("Description of the given dataset : \n" ,dataDesc,"\n")

Description of the given dataset : 
               Math      Reading      Writing
count  1000.000000  1000.000000  1000.000000
mean     67.290000    69.872000    68.616000
std      15.085008    14.657027    15.241287
min      13.000000    19.000000    14.000000
25%      58.000000    60.750000    58.000000
50%      68.000000    70.000000    69.500000
75%      78.000000    81.000000    79.000000
max     100.000000   100.000000   100.000000 



In [17]:
X = dataSet[['Math', 'Reading']]
Y = dataSet['Writing']

print("Features (X):")
print(X)

print("\nTarget (Y):")
print(Y)

Features (X):
     Math  Reading
0      48       68
1      62       81
2      79       80
3      76       83
4      59       64
..    ...      ...
995    72       74
996    73       86
997    89       87
998    83       82
999    66       66

[1000 rows x 2 columns]

Target (Y):
0      63
1      72
2      78
3      79
4      62
       ..
995    70
996    90
997    94
998    78
999    72
Name: Writing, Length: 1000, dtype: int64


In [23]:
X = dataSet[['Math', 'Reading']].to_numpy()
Y_actual = dataSet['Writing'].to_numpy()
X = X.T
d = X.shape[0]
W = np.random.rand(d, 1)
Y_pred = np.dot(W.T, X).T
print("Weight Vector (W):")
print(W)

print("\nFeature Matrix (X):")
print(X)

print("\nPredicted Target Vector (Y):")
print(Y_pred)
print("\nShapes:")
print("W:", W.shape)
print("X:", X.shape)
print("Y (predicted):", Y_pred.shape)


Weight Vector (W):
[[0.3600479 ]
 [0.75193759]]

Feature Matrix (X):
[[48 62 79 ... 89 83 66]
 [68 81 80 ... 87 82 66]]

Predicted Target Vector (Y):
[[ 68.41405478]
 [ 83.22991392]
 [ 88.59879055]
 [ 89.77445962]
 [ 69.36683128]
 [ 88.00606194]
 [ 88.36610983]
 [ 52.65520728]
 [ 80.61405327]
 [ 89.61525064]
 [ 74.20666289]
 [ 92.09395597]
 [ 53.24793588]
 [ 87.81501117]
 [ 74.59855258]
 [ 50.72760062]
 [ 74.99044227]
 [ 52.29515938]
 [ 93.23778324]
 [ 83.39891104]
 [ 67.37554103]
 [ 70.15061066]
 [ 78.26271512]
 [ 61.78377183]
 [ 89.14988922]
 [ 92.15763956]
 [ 71.95085014]
 [ 76.55800103]
 [ 88.17505906]
 [ 84.70194729]
 [ 83.46259463]
 [ 92.51768745]
 [ 78.68644661]
 [ 79.24733342]
 [ 52.7923626 ]
 [ 62.79044378]
 [ 57.85508678]
 [ 84.90278621]
 [ 80.48668608]
 [ 48.20726535]
 [ 91.70206628]
 [ 85.9829299 ]
 [ 70.02324348]
 [ 55.20738434]
 [ 73.09467741]
 [ 78.98281091]
 [ 58.21513468]
 [ 78.68644661]
 [107.5980691 ]
 [ 76.52615924]
 [111.19854805]
 [ 93.20594145]
 [ 83.22991392]
 [

In [22]:
from sklearn.model_selection import train_test_split
X = dataSet[['Math', 'Reading']].to_numpy()
Y = dataSet['Writing'].to_numpy()
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
print("Training set shapes:")
print("X_train:", X_train.shape, "Y_train:", Y_train.shape)

print("\nTest set shapes:")
print("X_test:", X_test.shape, "Y_test:", Y_test.shape)


Training set shapes:
X_train: (800, 2) Y_train: (800,)

Test set shapes:
X_test: (200, 2) Y_test: (200,)


In [27]:
def cost_function(X, Y, W):
    """
    Parameters:
    - X: Feature Matrix
    - Y: Target Matrix
    - W: Weight Matrix

    Output:
    - cost: Mean Squared Error
    """
    y_pred = np.dot(W.T, X).flatten()
    error = y_pred - Y
    cost = np.mean(error ** 2) / 2

    return cost


In [31]:
def cost_function(X, Y, W):
    """
    Parameters:
    - X: Feature Matrix
    - Y: Target Matrix
    - W: Weight Matrix

    Output:
    - cost: Mean Squared Error
    """
    y_pred = np.dot(X, W)
    error = y_pred.flatten() - Y
    cost = np.mean(error ** 2) / 2
    return cost

X_test = np.array([[1, 2], [3, 4], [5, 6]])
Y_test = np.array([3, 7, 11])
W_test = np.array([1, 1]).reshape(2, 1)
cost = cost_function(X_test, Y_test, W_test)
print("Cost function output:", cost)
if cost == 0:
    print("Proceed further.")
else:
    print("Something went wrong: Reimplement the cost function.")




Cost function output: 0.0
Proceed further.


In [34]:
def gradient_descent(X, Y, W, alpha, iterations):
    """
    Perform gradient descent to optimize the parameters of a linear regression model.

    Parameters:
    - X (numpy.ndarray): Feature matrix (m x n).
    - Y (numpy.ndarray): Target vector (m x 1).
    - W (numpy.ndarray): Initial guess for parameters (n x 1).
    - alpha (float): Learning rate.
    - iterations (int): Number of iterations for gradient descent.

    Returns:
    - W_update (numpy.ndarray): Updated parameters (n x 1).
    - cost_history (list): History of cost values over iterations.
    """
    m = len(Y)
    cost_history = [0] * iterations

    for iteration in range(iterations):
        Y_pred = np.dot(X, W)
        loss = Y_pred - Y
        dw = (1 / m) * np.dot(X.T, loss)
        W = W - alpha * dw
        cost = cost_function(X, Y, W)
        cost_history[iteration] = cost

    return W, cost_history

Optimized weights: [[-1.63106627 -3.80582129 -5.98057632]
 [ 1.91930476  4.47837777  7.03745078]]
Cost history: [51.513216666666665, 33.015808111296295, 24.001441516336346, 19.60129844576253, 17.446339850155162, 16.383853587978834, 15.852960202962045, 15.580750458947536, 15.434433855631319, 15.349397984668252, 15.294204104320352, 15.253554906662147, 15.220007081033453, 15.189938865366713, 15.161587962712135, 15.13409684301957, 15.107048212092986, 15.080238983000381, 15.053570296505942, 15.026994007904648, 15.000486648923118, 14.974036758265267, 14.947638716988859, 14.921289748961728, 14.894988461362537, 14.868734134526694, 14.842526376403946, 14.816364954426342, 14.790249713699541, 14.764180537196694, 14.738157326389684, 14.712179991824716, 14.686248448536483, 14.660362613816682, 14.634522406128156, 14.608727744576331, 14.582978548652012, 14.557274738105992, 14.531616232888, 14.506002953116816, 14.480434819065637, 14.45491175115479, 14.429433669948114, 14.404000496150994, 14.3786121506

In [36]:
np.random.seed(0)
X = np.random.rand(100, 3)
Y = np.random.rand(100)
W = np.random.rand(3)
alpha = 0.01
iterations = 1000
final_params, cost_history = gradient_descent(X, Y, W, alpha, iterations)
print("Final Parameters:", final_params)
print("Cost History:", cost_history)

Final Parameters: [0.20551667 0.54295081 0.10388027]
Cost History: [0.10711197094660153, 0.10634880599939901, 0.10559826315680618, 0.10486012948320558, 0.1041341956428534, 0.10342025583900626, 0.1027181077540776, 0.1020275524908062, 0.10134839451441931, 0.1006804415957737, 0.1000235047554587, 0.09937739820884377, 0.09874193931205609, 0.09811694850887098, 0.09750224927850094, 0.0968976680842672, 0.09630303432313951, 0.09571818027612913, 0.09514294105952065, 0.09457715457692842, 0.09402066147216397, 0.09347330508290017, 0.09293493139511913, 0.09240538899833017, 0.09188452904154543, 0.0913722051899995, 0.09086827358260123, 0.09037259279010502, 0.08988502377398919, 0.08940542984603007, 0.08893367662855953, 0.08846963201539432, 0.08801316613342668, 0.08756415130486386, 0.08712246201010665, 0.08668797485125508, 0.08626056851623207, 0.08584012374351278, 0.08542652328745133, 0.08501965188419301, 0.0846193962181636, 0.08422564488912489, 0.08383828837978763, 0.08345721902397185, 0.08308233097530

In [37]:
def rmse(Y, Y_pred):
    """
    Calculate the Root Mean Squared Error (RMSE).

    Parameters:
    - Y: Actual target values (1D array).
    - Y_pred: Predicted target values (1D array).

    Returns:
    - rmse: Root Mean Squared Error.
    """
    n = len(Y)
    rmse = np.sqrt(np.sum((Y - Y_pred) ** 2) / n)
    return rmse


In [38]:
def r2(Y, Y_pred):
    """
    Calculate the R Squared (coefficient of determination) value.

    Parameters:
    - Y: Actual target values (1D array).
    - Y_pred: Predicted target values (1D array).

    Returns:
    - r2: R Squared value.
    """
    n = len(Y)
    mean_y = np.mean(Y)
    ss_total = np.sum((Y - mean_y) ** 2)
    ss_residual = np.sum((Y - Y_pred) ** 2)
    r2 = 1 - (ss_residual / ss_total)
    return r2


In [43]:
# Main Function
def main():
    X = dataSet[['Math', 'Reading']].values
    Y = dataSet['Writing'].values
    X_mean = X.mean(axis=0)
    X_std = X.std(axis=0)
    X_normalized = (X - X_mean) / X_std
    X_train, X_test, Y_train, Y_test = train_test_split(X_normalized, Y, test_size=0.2, random_state=42)
    W = np.zeros(X_train.shape[1])
    alpha = 0.0001
    iterations = 1000
    W_optimal, cost_history = gradient_descent(X_train, Y_train, W, alpha, iterations)
    Y_pred = np.dot(X_test, W_optimal)
    model_rmse = rmse(Y_test, Y_pred)
    model_r2 = r2(Y_test, Y_pred)
    print("Final Weights:", W_optimal)
    print("Cost History (First 10 iterations):", cost_history[:10])
    print("RMSE on Test Set:", model_rmse)
    print("R-Squared on Test Set:", model_r2)
if __name__ == "__main__":
    main()


Final Weights: [1.06484959 1.40144515]
Cost History (First 10 iterations): [2471.6620474310935, 2471.6253575184387, 2471.5886802576224, 2471.552015644236, 2471.5153636738696, 2471.4787243421174, 2471.4420976445736, 2471.405483576834, 2471.3688821344967, 2471.332293313161]
RMSE on Test Set: 69.78693505233176
R-Squared on Test Set: -18.456124807688028
